---
title: "Communications"
format: html
---

The Conversation: '[Thousands of dead puffins are washing up on Europe's beaches - why it's been such a dangerous winter for seabirds](https://theconversation.com/thousands-of-dead-puffins-are-washing-up-on-europes-beaches-why-its-been-such-a-dangerous-winter-for-seabirds-276545)'

Lancaster University press release: '[On-board camera footage offers bird's eye glimpse into seabird flights and feeding behaviour](https://www.lancaster.ac.uk/news/on-board-camera-footage-offers-birds-eye-glimpse-into-seabird-flights-and-feeding-behaviour)'

Lancaster University press release: ['Restored rat-free islands could support hundreds of thousands more breeding seabirds'](https://www.lancaster.ac.uk/news/restored-rat-free-islands-could-support-hundreds-of-thousands-more-breeding-seabirds)

Lancaster University press release: ['How foraging tropical seabirds choose where to feed'](https://www.lancaster.ac.uk/sci-tech/about-us/news/how-foraging-tropical-seabirds-choose-where-to-feed)

['Counting Calories for Seabirds'](https://hakaimagazine.com/news/counting-calories-for-seabirds/) by Rebecca Heisman for Hakai Magazine

The Conversation: ['Struggling seabirds thrown a lifeline by new commercial fishing ban in the North Sea, but it may not be enough'](https://theconversation.com/struggling-seabirds-thrown-a-lifeline-by-new-commercial-fishing-ban-in-the-north-sea-but-it-may-not-be-enough-223171)

Journal of Experimental Biology: ['Early Career Researcher Spotlight Interview: Ruth Dunn and James Duckworth'](https://doi.org/10.1242/jeb.247067)

University of Liverpool press release: ['How do puffins catch food outside the breeding season?'](https://news.liverpool.ac.uk/2019/07/10/how-puffins-catch-food-outside-the-breeding-season/)

University of Liverpool press release: ['New app to estimate rates of metabolism in seabirds'](https://www.liverpool.ac.uk/study/postgraduate-research/news/articles/new-app-to-estimate-rates-of-metabolism-in-seabirds)
