---
title: "Publications"
format: html
---

​Please get in touch if you struggle to access any of these articles and I'll try and help.

### 2026

Neumann JL, **Dunn RE**, Nicoll MAC, Larose CS, Foster C, Brodin G, Feare CJ. (2026) Foraging areas of breeding sooty terns *Onychoprion fuscatus* on Bird Island, Seychelles. *Marine Ornithology*. 54: 131-138. [doi.org/10.5038/2074-1235.54.1.1682](http://www.marineornithology.org/article?rn=1682).

### 2025

**Dunn RE**, Trevail AM, Nicoll MAC, Freeman R, Braman CA, Clark BL, Mitchell C, Schiffmiller AW, Wood H, Votier SC. (2025) Commuting in crosswinds and foraging in fast winds: the foraging ecology of a flying fish specialist. *Proceedings of the Royal Society B*. 292: 20250774. [doi.org/10.1098/rspb.2025.0774](https://doi.org/10.1098/rspb.2025.0774){.uri}.

See [here](https://www.lancaster.ac.uk/news/on-board-camera-footage-offers-birds-eye-glimpse-into-seabird-flights-and-feeding-behaviour) for a Lancaster University news article on this publication.

**Dunn RE**, Graham NAJ, Jeannot LL, Karkarey R, Gonzalez-Barrios FJ, Lange ID, Rodriquez Fillol J, Roche R, Stuhr M, Benkwitt C. (2025) Active and passive pathways of nutrient transfer in coral reef ecosystems. *Coral Reefs*. 44: 1157-1170. [doi.org/10.1007/s00338-025-02676-z](https://doi.org/10.1007/s00338-025-02676-z){.uri}.

See [here](https://www.lancaster.ac.uk/lec/about-us/news/ocean-currents-and-bird-colonies-work-together-to-keep-coral-reefs-healthy) for a Lancaster University news article on this publication.

Jones HP, Appoo J, Benkwitt CE, Borrelle SB, **Dunn RE**, Epstein HE, Fowlke LA, Holmes ND, Jeanott LL, Malhi Y, Rankin LL, Steibl S, Wails CN, Will DJ, Graham NAJ. (2025) The circular seabird economy is critical for oceans, islands, and people. *Nature Reviews Biodiversity.* [doi.org/10.1038/s44358-025-00099-w](https://doi.org/10.1038/s44358-025-00099-w).

See [here](https://www.lancaster.ac.uk/news/global-study-reveals-seabirds-as-critical-connectors-between-islands-the-ocean-and-people) for an Lancaster University news article on this publication.

Trevail AM, **Dunn RE**, Carr P, Esteban N, Freeman R, Harris JL, Nicoll MAC, Stephens N, Stevens GMW, Votier SC, Wood H, Hays GC. (2025) Large marine protected areas can encompass movements of diverse megafauna. *Journal of Applied Ecology*. [doi.org/10.1111/1365-2664.70117](https://doi.org/10.1111/1365-2664.70117){.uri}.

See [here](https://news.exeter.ac.uk/faculty-of-environment-science-and-economy/chagos-study-highlights-value-of-vast-marine-protected-areas/) for an Exeter University news article on this publication.

Ravenswater HM, Burthe SJ, Reed TE, Newell MA, Daunt F, Carravieri A, **Dunn RE**, Granroth-Wilding HHV, Gunn C, Hicks O, Cunningham EJA. (2025) Temporal variation in early-life conditions impacts on later-life levels of infection in sex specificways. *Ecology and Evolution*. 15: e72132. [doi.org/10.1002/ece3.72132](https://doi.org/10.1002/ece3.72132).

Teixeira H, Nicoll MAC, Jaeger A, Bunbury N, Choeur A, A'Bear L, Lebarbenchon C, Bielsa M, **Dunn RE**, Freeman R, Jivan Shah N, Rocamora G, Calabrese L, Trevail AM, Tourmetz J, Votier SC, Le Corre M, Humeau L. (2025) Genetic differentiation in a wide-ranging tropical seabird in the Indian Ocean is linked with oceanographic factors. *Diversity and Distributions*. 31: e70078. [doi.org/10.1111/ddi.70078](https://doi.org/10.1111/ddi.70078).

Spencer ET, Hoopes LA, Morris JJ, Chapman DD, Hagan V, Johnson M, Payne NL, Watanabe YY, **Dunn RE**, Papastamatiou YP. (2025) Energetic benefits of prey choice for a shark-eating shark. *Oecologia*. 207: 113. [doi.org/10.1007/s00442-025-05758-5](https://doi.org/10.1007/s00442-025-05758-5){.uri}.

Coste J, Votier SC, **Dunn RE**, Freeman R, Nicoll MA, Carr P, Wood H, Trevail AM. (2025) Homing navigation is optimized to diurnal constraints in a tropical seabird, the red-footed booby. *Animal Behaviour*. 222: 123116. [doi.org/10.1016/j.anbehav.2025.123116](https://doi.org/10.1016/j.anbehav.2025.123116){.uri}.

Buckingham L, Bogdanova MI, Daunt F, Furness RW, Bennett S, **Dunn RE**, Jardine DC, Newell MA, Weston ED, Green JA. (2025) An improved method to derive behavioural budgets and energetics from geolocator data in Common Guillemots Uria aalge. *Seabird*. 37: 73-92. [doi.org/10.61350/sbj.37.6](https://doi.org/10.61350/sbj.37.6).

### 2024

**Dunn RE**. (2024) Atolls are vital for seabirds and vice versa. *Nature Ecology & Evolution*. 8: 1784-1785. [doi.org/10.1038/s41559-024-02518-1](https://doi.org/10.1038/s41559-024-02518-1).

**Dunn RE**, Benkwitt CE, Maury O, Barrier N, Carr P, Graham NAJ. (2024) Island restoration to rebuild seabird populations and amplify coral reef functioning. *Conservation Biology*. 39: e14313. [doi.org/10.1111/cobi.14313](https://doi.org/10.1111/cobi.14313){.uri}.

See [here](https://www.lancaster.ac.uk/news/restored-rat-free-islands-could-support-hundreds-of-thousands-more-breeding-seabirds/) for a Lancaster University news article on this publication.

**Dunn RE**, Freeman R, Nicoll MA, Ramsden J, Trevail AM, Wood H, Votier SC. (2024) From route to dive: multi-scale habitat selection in a foraging tropical seabird. *Marine Biology*. 171: 124. [doi.org/10.1007/s00227-024-04445-y](https://doi.org/10.1007/s00227-024-04445-y){.uri}.

See [here](https://portal.lancaster.ac.uk/portal/news/article/how-foraging-tropical-seabirds-choose-where-to-feed) for a Lancaster University news article on this publication.

**Dunn RE**, Duckworth J, O’Brien S, Furness RW, Buckingham L, Daunt L, Bogdanova MI & Green JA. (2024) Temporal and spatial variability in availability bias has consequences for marine bird abundance estimates during the non-breeding season. *Ecological Solutions and Evidence*. 5: e12373. [doi.org/10.1002/2688-8319.12373](https://doi.org/10.1002/2688-8319.12373){.uri}.

See [here](https://appliedecologistsblog.com/2024/10/15/beneath-the-waves-estimating-marine-bird-abundances-outside-the-breeding-season/) for a blog article about this manuscript.

Dedman S, Moxley JH, Papastamatiou YP, Braccini M, Caselle JE, Chapman DD, Cinner JE, Dillon EM, Dulvy NK, **Dunn RE**, Espinoza M, Harborne AR, Harvey ES, Heupel MR, Huveneers C, Graham NAJ, Ketchum JT, Klinard NV, Kock AA, Lowe CG, MacNeil AM, Madin EMP, McCauley DJ, Meekan MG, Meier AC, Simpfendorfer CA, Tinker MT, Winton, M, Wirsing AJ, Heithaus MR. (2024) Ecological roles and importance of sharks in the Anthropocene Ocean. *Science*. 385: 6708. [doi.org/10.1126/science.adl2362](https://doi.org/10.1126/science.adl2362){.uri}.

See [here](https://www.lancaster.ac.uk/news/big-sharks-equal-big-impact-but-theres-a-big-problem) for a Lancaster University news article on this publication.

Duckworth J, O'Brien S, **Dunn RE**, Petersen IK, Petersen A, Benediktsson G, Johnson L, Lehikoinen P, Okill DJ, Väisänen R, Williams J, Williams S, Daunt F, Green JA. (2024) Linking foraging behaviour and habitat preferences during moult across multiple populations of red-throated diver. *Ecology and Evolution*. 14 (12): 1-15. [doi.org/10.1002/ece3.70733](https://doi.org/10.1002/ece3.70733){.uri}.

Votier SC, Corcoran G, Carr P, **Dunn RE**, Freeman R, Nicoll MA, Wood H, Trevail AM. (2024) Geolocation and immersion loggers reveal year-round residency and consequent nutrient deposition rates of adult red-footed boobies in the Chagos Archipelago, tropical Indian Ocean. *Journal of Avian Biology*. 9-10: e03185. [doi.org/10.1111/jav.03185](https://doi.org/10.1111/jav.03185){.uri}.

Bennett S, Daunt F, Searle KR, Harris MP, Buckingham L, Duckworth J, Wanless S, **Dunn RE**, Newell MA, Green JA. (2024) Distribution and time budgets limit occupancy of breeding sites in the nonbreeding season in a colonial seabird. *Animal Behaviour*. 216: 213-233. [doi.org/10.1016/j.anbehav.2024.07.023](https://doi.org/10.1016/j.anbehav.2024.07.023){.uri}.

Healing S, Benkwitt CE, **Dunn RE**, Graham NAJ. (2024) Seabird-vectored pelagic nutrients integrated into temperate intertidal rocky shores. *Frontiers in Marine Science*. 11: 1343966. [doi.org/10.3389/fmars.2024.1343966](https://doi.org/10.3389/fmars.2024.1343966){.uri}.

### 2023

**Dunn RE**\*, Duckworth J\*, Green JA. (2023) A framework to unlock marine bird energetics. *Journal of Experimental Biology*. 226 (24): jeb246754. [doi.org/10.1242/jeb.246754](https://doi.org/10.1242/jeb.246754){.uri} \* contributed equally.

See [here](https://journals.biologists.com/jeb/article/226/24/jeb247067/338274/ECR-Spotlight-Ruth-Dunn-and-James-Duckworth) for an interview with me and co-lead author, James Duckworth.

Benkwitt CE, D'Angelo C, **Dunn RE**, Gunn RL, Healing S, Mardones ML, Wiedenmann J, Wilson SK, Graham NAJ. (2023) Seabirds boost coral reef resilience. *Science Advances*. 9: eadj039. [doi.org/10.1126/sciadv.adj0390](https://doi.org/10.1126/sciadv.adj0390).

See [here](https://www.lancaster.ac.uk/news/feathered-friends-can-become-unlikely-helpers-for-tropical-coral-reefs-facing-climate-change-threat) for a Lancaster University news article on this publication.

Trevail AM, Wood H, Carr P, **Dunn RE**, Nicoll MA, Votier SC, Freeman R. (2023) Multi-colony tracking reveals segregation in foraging range, space use, and timing in a tropical seabird. *Marine Ecology Progress Series*. 724: 155-165. [doi.org/10.3354/meps14479](https://doi.org/10.3354/meps14479){.uri}.

Metcalfe NB, Bellman J, Bize P, Blier PU, Crespel A, Dawson NJ, **Dunn RE**, Halsey LG, Hood WR, Hopkins M, Killen SS, McLennan D, Nadler LE, JJH Nati, Noakes MJ, Norin T, Ozanne SE, Peaker M, Pettersen AK, Przybylska-Piech A, Rathery A, Récapet C, Rodríguez E, Salin K, Stier A, Thoral E, Westerterp KR, Westerterp-Plantenga MS, Wojciechowski MS, Monaghan P. (2023) Solving the conundrum of intra-specific variation in metabolic rate: a multidisciplinary conceptual and methodological toolkit. *BioEssays*. 45 (6): 2300026. [doi.org/10.1002/bies.202300026](https://doi.org/10.1002/bies.202300026).

Buckingham L, Daunt F, Bogdanova MI, Furness RW, Bennett S, Duckworth J, **Dunn RE**, Wanless S, Harris MP, Jardine DC, Newell MA, Ward RM, Weston ED, Green JA. (2023) Energetic synchrony throughout the non-breeding season in common guillemots from four colonies. *Journal of Avian Biology*. 1-2: e03018. [doi.org/10.1111/jav.03018](https://doi.org/10.1111/jav.03018).

### 2022

**Dunn RE**, Green J, Wanless S, Harris MP, Newell MA, Bogdanova MI, Horswill C, Daunt F, Matthiopoulos J. (2022) Modelling and mapping how common guillemots balance their energy budgets over a full annual cycle. *Functional Ecology*. 36 (7): 1612-1626. [doi.org/10.1111/1365-2435.14059](https://doi.org/10.1111/1365-2435.14059){.uri}.

See [here](https://fesummaries.wordpress.com/2022/04/22/a-new-approach-to-investigate-wild-animal-energy-budgets/) for a plain language summary of this publication.

**Dunn RE**, Bradley D, Heithaus MR, Caselle JE, Papastamatiou YP. (2022) Conservation implications of forage base requirements of a marine predator population at carrying capacity. *iScience*. 25 (1): 103646. [doi.org/10.1016/j.isci.2021.103646](https://doi.org/10.1016/j.isci.2021.103646){.uri}.

Heithaus MR, **Dunn RE**, Farabaugh NF, Lester E, Madin E, Meekan M, Papastamatiou YP, Roff G, Vaudo JJ, Wirsing AJ. (2022) Advances in Our Understanding of the Ecological Importance of Sharks and Their Relatives. Biology of Sharks and Their Relatives, Third Edition, edited by Carrier JC, Simpfendorfer CA, Heithaus MR, Yopak KE. CRC Press.

Buckingham L, Bogdanova MI, Green JA, **Dunn RE**, Wanless S, Bennett S, Bevan RM, Call A, Canham M, Corse CJ, Harris MP, Heward CJ, Jardine DC, Lennon J, Parnaby D, Redfern CPF, Scott L, Swann RL, Ward RM, Weston ED, Furness RW, Daunt F. (2022) Interspecific variation in non-breeding aggregation: a multi-colony tracking study of two sympatric seabirds. *Marine Ecology Progress Series*. 684: 181-197. [doi.org/10.3354/meps13960](https://doi.org/10.3354/meps13960){.uri}.

### 2021

**Dunn RE**, Buckingham L, Bogdanova MI, Daunt F, Newell MA. (2021) Two observations of acorn barnacles attached to GLS loggers on seabirds in the North Atlantic. *Seabird*. 33: 115-118. [doi.org/10.61350/sbj.33.115](https://doi.org/10.61350/sbj.33.115).

### 2020

**Dunn RE**, Wanless S, Daunt F, Harris MP, Green JA. (2020) A year in the life of a North Atlantic seabird: behavioural and energetic adjustments during the annual cycle. *Scientific Reports*. 10: 5933. [doi.org/10.1038/s41598-020-62842-x](https://doi.org/10.1038/s41598-020-62842-x){.uri}.

See [here](https://seguliverpool.wixsite.com/home/post/a-year-in-the-life-of-a-north-atlantic-seabird) for a blog post about this publication.

Vye SR, Dickens S, Delany J, Adams L, Bohn K, Chenery J, Dobson N, **Dunn RE**, ​Earp HS, Evans M, Foster C, Grist H, Holt B, Hull S, Jenkins SR, Lamont P, Long S, Mieszkowska N, Millard J, Morrall Z, Pack K, Parry-Wilson H, Pocklington J, Pottas J, Richardson L, Scott A, Sugden H, Watson G, West V, Winton D, Delany J, Burrows MT. (2020) Patterns of abundance across geographical ranges as a predictor for responses to climate change: evidence from UK rocky shores. *Diversity and Distributions*. 26: 1357-1365. [doi.org/10.1111/ddi.13118](https://doi.org/10.1111/ddi.13118).

### 2019

**Dunn RE**, Wanless S, Green JA, Harris MP, Daunt F. (2019) Effects of body size, sex, parental care and moult strategies on auk diving behaviour outside the breeding season. *Journal of Avian Biology*. 50 (7): 02012. [doi.org/10.1111/jav.02012](https://doi.org/10.1111/jav.02012).

See [here](https://news.liverpool.ac.uk/2019/07/10/how-puffins-catch-food-outside-the-breeding-season/) for a University of Liverpool news article on this publication.

### 2018

**Dunn RE**, White CR, Green JA. (2018) A model to estimate seabird field metabolic rates. *Biology Letters*. 14 (6): 20180190. [doi.org/10.1098/rsbl.2018.0190](http://dx.doi.org/10.1098/rsbl.2018.0190){.uri}.

See [here](https://www.liverpool.ac.uk/study/postgraduate-research/news/articles/new-app-to-estimate-rates-of-metabolism-in-seabirds) for a University of Liverpool news article on this publication.
